BO:
  batch_size: 2
  iteration: 0
  n_init_samples: 5
  n_iterations: 2
  objective:
  - saxs
  - uvvis
  weights:
  - 0.5
  - 0.5
Default:
  mode: simulation
  num_grid_perdim: 5
  oracle_call: 1
  r_mu: 20
  r_sigma: 1e-2
  savedir: ./output/
Modelling:
  n_sas_samples: 191
  n_structures: 4
  n_uvvis_samples: 121
Targets:
  dls: null
  saxs: ../data/rods_target.xlsx
  uvvis: ../data/Rods_from_manufacturer.xlsx
